# Generated by Django 2.1 on 2018-08-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ids', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('state', models.SmallIntegerField()),
                ('user_id', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycom_transaction_id', models.CharField(max_length=25)),
                ('paycom_time', models.CharField(max_length=13)),
                ('paycom_time_datetime', models.DateField()),
                ('create_time', models.DateField()),
                ('perform_time', models.DateField()),
                ('cancel_time', models.DateField()),
                ('amount', models.IntegerField()),
                ('state', models.SmallIntegerField()),
                ('reason', models.SmallIntegerField()),
                ('receivers', models.CharField(max_length=500)),
                ('order_id', models.IntegerField()),
            ],
        ),
    ]
