# Generated by Django 2.1 on 2018-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_ids', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('state', models.SmallIntegerField()),
                ('user_id', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
